khailamconsulting/khailamconsulting.github.io

alelo/assets/js/components/main.vue
alelo/assets/js/components/main/archived_class.vue
alelo/assets/js/components/main/class_list.vue
alelo/assets/js/components/main/class_student.vue
alelo/assets/js/components/main/class_view.vue
alelo/assets/js/components/main/popup/create_class_modal.vue
alelo/assets/js/components/main/popup/notice_modal.vue
alelo/assets/js/components/main/routes.js
alelo/assets/js/components/main/tab_list.vue
alelo/assets/js/config/ajax_caller.js
alelo/assets/js/config/store.js

- Check the attributes `response.data.success`, if it is `false`, show notice message
- Update the API params, ensure send param id when update student, class...

Api feedback

---

alelo/assets/js/components/main/class_student.vue
alelo/assets/js/components/main/class_view.vue
alelo/assets/js/components/main/class_view/active_course_list.vue
alelo/assets/js/components/main/class_view/course_simulation_list.vue
alelo/assets/js/services/sorter.js

- Sort the Title by default on the Class Student Simulation List
- Sort the Last Login by default on the Class Detail Student List
- Sort the Course Name by default on  the Class Detail Active Course List
- Sort the Simulation Title by default on  the Course Simulation Modal
- Split the Active Course List and Course Simulation List to the smaller separate components

Add default order

---

alelo/assets/js/components/main/popup/create_class_modal.vue
alelo/assets/js/config/app.js
alelo/assets/js/config/store.js
alelo/assets/js/lang/en.json

We can config the validation message with i18n

Config i18n for validation message

---

alelo/assets/js/components/main/class_student.vue
alelo/assets/js/components/main/class_view.vue
alelo/assets/js/components/main/popup/student_simulation_detail.vue
alelo/assets/js/config/app.js
alelo/assets/js/config/filters.js
alelo/package-lock.json
alelo/package.json

Default sort student modal, paginate and global filters

---

alelo/assets/css/main.scss
alelo/assets/js/components/main/class_student.vue
alelo/assets/js/config/store.js
alelo/assets/js/main.js
alelo/assets/js/services/horizontal_scroll_bar_handler.js

video:
https://drive.google.com/file/d/1ZHD5TVpnhwEh4acbmgMROi9hDoLGECk7/view?usp=sharing

Fixing issue 50

---

alelo/assets/js/components/main/class_student.vue

Sort the courses by name on class student

---

alelo/assets/css/main.scss
alelo/assets/js/components/main/new_class/courses_form.vue
alelo/assets/js/components/main/new_class/information_form.vue
alelo/assets/js/components/main/new_class/new_class_wizard.vue
alelo/assets/js/lang/en.json

New class wizard courses form

---

alelo/assets/js/components/main/new_class/students_form.vue
alelo/assets/js/lang/en.json

New class wizard: Build the students form

---

alelo/assets/css/main.scss
alelo/assets/js/components/main/new_class/courses_form.vue
alelo/assets/js/components/main/new_class/information_form.vue
alelo/assets/js/components/main/new_class/new_class_wizard.vue
alelo/assets/js/components/main/new_class/review_form.vue
alelo/assets/js/components/main/popup/create_class_modal.vue
alelo/assets/js/lang/en.json

New class wizard: Review form

---

alelo/assets/css/main.scss
alelo/assets/js/components/common/dropdown_button.vue
alelo/assets/js/components/main/class_view.vue
alelo/assets/js/components/main/new_class/information_form.vue
alelo/assets/js/components/main/new_class/new_class_wizard.vue
alelo/assets/js/components/main/popup/edit_class_modal.vue

Edit class modal

---

alelo/assets/css/main.scss
alelo/assets/js/components/main/class_view.vue
alelo/assets/js/components/main/new_class/available_courses_table.vue
alelo/assets/js/components/main/new_class/courses_form.vue
alelo/assets/js/components/main/popup/add_courses_modal.vue

Edit course modal

---

alelo/assets/css/main.scss
alelo/assets/js/components/common/dropdown_button.vue

Display the selected institution instead of the default label

Issue 79: Fix the selected value of dropdown button

---

alelo/assets/js/components/main/class_list.vue

Re-init scroll bar when back to Class List from Class Viewer

Init scroll bar when back to class list from class viewer

---

alelo/assets/js/components/main/new_class/students_form.vue
alelo/assets/js/components/main/popup/add_courses_modal.vue
alelo/assets/js/components/main/popup/add_student_modal.vue
alelo/assets/js/components/main/popup/edit_class_modal.vue
alelo/assets/js/config/ajax_caller.js
alelo/assets/js/config/store.js
alelo/assets/js/mixins/student_email.js

Update API endpoint and params

---

alelo/assets/js/components/main/new_class/available_courses_table.vue
alelo/assets/js/components/main/popup/add_courses_modal.vue

Class View - Add Course functionality

---

alelo/assets/css/main.scss
alelo/assets/js/components/main.vue
alelo/assets/js/components/main/loader.vue
alelo/assets/js/config/ajax_caller.js
alelo/assets/js/config/app.js
alelo/assets/js/config/store.js

https://user-images.githubusercontent.com/17775345/106609828-98ec7600-6598-11eb-9b43-5246b4ff6093.mov

Loading page after submitting the request

---

alelo/assets/css/main.scss
alelo/assets/js/components/main/new_class/information_form.vue
alelo/assets/js/components/main/new_class/new_class_wizard.vue
alelo/assets/js/components/main/new_class/progress_bar.vue
alelo/assets/js/lang/en.json
alelo/assets/styles/jquery.scrollbar.css

fixed_issue_ui: fixed issue UI

---

alelo/assets/js/components/common/dropdown_button.vue
alelo/assets/js/components/main/class_view.vue
alelo/assets/js/config/ajax_caller.js
alelo/assets/js/config/store.js

Add endpoint delete student and resend invitation

---

alelo/assets/css/main.scss
alelo/assets/js/components/footer.vue
alelo/assets/js/lang/en.json

issue_103: Change the footer

---

alelo/assets/js/components/main/new_class/information_form.vue
alelo/assets/js/components/main/new_class/new_class_wizard.vue
alelo/assets/js/components/main/popup/edit_class_modal.vue

Class Name -- Add a character limit to class names

---

alelo/assets/js/components/main/class_view.vue
alelo/assets/js/config/filters.js

Adjust resend invitation

---

alelo/assets/js/components/common/kl_datepicker.vue
alelo/assets/js/components/main/new_class/information_form.vue
alelo/assets/js/lang/en.json
alelo/package-lock.json
alelo/package.json

My bad, when enabled the filling feature, I make the select date function was wrong
Fixes #114 
I also adjust the validate message, please take a look and let me know if it not ok
https://user-images.githubusercontent.com/17775345/111656593-419b2000-883d-11eb-8111-c7e099261651.mp4

Issue 114. Adjust class dates

---

alelo/assets/js/components/main/class_view.vue

https://user-images.githubusercontent.com/17775345/112319960-26b72880-8ce1-11eb-8428-f47cd1ebd472.mp4

Fix modal gray

---

alelo/assets/js/components/main/class_view.vue
alelo/assets/js/components/main/popup/add_courses_modal.vue

Fix add course issue

---

alelo/assets/js/components/main/class_student.vue
alelo/assets/js/components/main/class_view.vue
alelo/assets/js/components/main/popup/student_simulation_detail.vue
alelo/assets/js/config/ajax_caller.js
alelo/assets/js/config/store.js

Implement the Download button
